version: "3"
services:
  grafana:
    image: grafana/grafana:latest
    ports:
    - "3000:3000"
    volumes:
    - /var/lib/grafana
    environment:
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}

    # These creds are hardcoded, but it's okay because they're only used on localhost
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=admin # pragma: allowlist secret
  grafana-setup:
    image: governmentpaas/terraform:terraform-0.13.3
    depends_on:
    - grafana
    restart: "no"
    volumes:
    - ./terraform:/terraform:ro
    - /terraform-data-dir
    - /terraform-state-dir
    entrypoint:
    - sh
    - -c
    - |
      set -eu

      while ! wget -q -O - http://grafana:3000/api/health | grep "ok"; do
        echo "Waiting for grafana to be ready..."
        sleep 1
      done

      export TF_DATA_DIR=/terraform-data-dir
      cd /terraform
      terraform init -backend-config path=/terraform-state-dir/terraform.tfstate
      terraform apply -auto-approve -var grafana_url="http://grafana:3000"

