#!/bin/bash

echo "Starting up the admin machine!"

# Source DISTRIB_* env vars
# shellcheck disable=SC1091
. /etc/lsb-release

export DEBIAN_FRONTEND=noninteractive

echo "[$(date '+%H:%M:%S %d-%m-%Y')] configure locales ..."
echo "LC_ALL=en_GB.UTF-8" > /etc/environment
locale-gen "en_GB.UTF-8"
dpkg-reconfigure locales

echo "[$(date '+%H:%M:%S %d-%m-%Y')] ensure the packages are up to date ..."
apt-get update -qq
apt-get -y upgrade

echo "[$(date '+%H:%M:%S %d-%m-%Y')] install AWS cli ..."
apt-get -y install awscli jq

echo "[$(date '+%H:%M:%S %d-%m-%Y')] installing docker ..."
apt-get -y install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

apt-get -y install docker-ce docker-ce-cli containerd.io

echo "[$(date '+%H:%M:%S %d-%m-%Y')] END SNIPPET: done provisioning the admin machine!"
