# This merely places the provided `family` of the task definition into the
# outputs.
platform: linux
image_resource:
  type: docker-image
  source:
    repository: govuk/ecs-cli
    tag: latest
    username: ((docker_hub_username))
    password: ((docker_hub_authtoken))
outputs:
  - name: task-definition-arn
params:
  APPLICATION:
run:
  path: sh
  args:
    - '-c'
    - |
      set -eu
      echo $APPLICATION > "task-definition-arn/task-definition-arn"
